spring:
  application:
    name: storage-task
  datasource:
    url: jdbc:h2:mem:storage
    username: root
    password: ${PWD}
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  liquibase:
    change-log: db/changelog/db.changelog-master.xml
server:
  port: ${SERVER_PORT:8081}