version: "3.9"

services:
  storage:
    image: 'postgres:16'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: storage
      PGDATA: "/var/lib/postgresql/data/docker-data/storage"
    ports:
      - "5432:5432"
#  app:
#    build:
#      context: .
#      dockerfile: ./Dockerfile
#    environment:
#      - 'DATABASE_HOST=db'
#      - 'DATABASE_PORT=${DATABASE_PORT}'
#      - 'DATABASE_DB=${DATABASE_DB}'
#      - 'DATABASE_USERNAME=${DATABASE_USERNAME}'
#      - 'DATABASE_PASSWORD=${DATABASE_PASSWORD}'
#    ports:
#      - "8189:8189"
#    links:
#      - storage

#  storage-task:
#    build: .
#    container_name: storage-task
#    ports:
#          - "8080:8080"
#    environment:
#            - SPRING_PROFILES_ACTIVE=docker
#    volumes:
#            - ./logs:/app/logs
#    networks:
#            - my -network








